import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next js tutorial",
    template: "%s | Next js tutorial",
    // absolute: "", overwrites all parent segment titles
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ background: "lightblue", padding: "1rem" }}>
          Header
        </header>
        <main>{children}</main>
        <footer style={{ background: "ghostwhite", padding: "1rem" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
